
# Comment to be posted on first time issues.
newIssueWelcomeComment: |
  ğŸ‘‹ Thanks for opening your first issue here! If you're reporting a ğŸ bug, please make sure you include particular steps to reproduce it.

# Comment to be posted on PRs from first time contributors.
newPRWelcomeComment: |
  ğŸ’– Thanks for opening this pull request! ğŸ’–

# Comment to be posted on pull requests merged by a first time user.
firstPRMergeComment: >
  Congrats on merging your first pull request and thank you for your contribution! ğŸ‰ğŸ‰ğŸ‰